jax:
  url: https://github.com/google/jax.git
  tracking_ref: main
  latest_verified_commit: f9a90ff249f3fcf0ae177a235d912df434a7c0ff
  mode: git-clone
xla:
  url: https://github.com/openxla/xla.git
  tracking_ref: main
  latest_verified_commit: 9500b6e2d258742a3105b257ece797c12672d16d
  mode: git-clone
flax:
  url: https://github.com/google/flax.git
  mirror_url: https://github.com/nvjax-svc-0/flax.git
  tracking_ref: main
  latest_verified_commit: d87f7da77e2b39eb219e46c1616114a587429e0f
  mode: git-clone
  patches:
    pull/3340/head: file://patches/flax/PR-3340.patch # Add Sharding Annotations to Flax Modules
transformer-engine:
  url: https://github.com/NVIDIA/TransformerEngine.git
  tracking_ref: main
  latest_verified_commit: dccf67e7b3b70cc3d30a2e071e51a83c31d17e31
  mode: git-clone
t5x:
  url: https://github.com/google-research/t5x.git
  mirror_url: https://github.com/nvjax-svc-0/t5x.git
  tracking_ref: main
  latest_verified_commit: fb02040e4c7e7a910ccaed1bc69053981307e451
  mode: git-clone
  patches:
    mirror/patch/partial-checkpoint-restore: file://patches/t5x/mirror-patch-partial-checkpoint-restore.patch # pull/1392/head  # https://github.com/google-research/t5x/pull/1392: Add support for partial checkpoint restore
    mirror/patch/dali-support: file://patches/t5x/mirror-patch-dali-support.patch # pull/1393/head  # https://github.com/google-research/t5x/pull/1393: Adds DALI support to t5x
    mirror/patch/t5x_te_in_contrib_noindent: file://patches/t5x/mirror-patch-t5x_te_in_contrib_noindent.patch # pull/1391/head  # https://github.com/google-research/t5x/pull/1391: Adds transformer engine support and GPU optimizations to T5x (enables H100)
paxml:
  url: https://github.com/google/paxml.git
  mirror_url: https://github.com/nvjax-svc-0/paxml.git
  tracking_ref: main
  latest_verified_commit: caa6913e79f684efe4535dfb2e8042ba2c32ed3c
  mode: git-clone
  patches:
    pull/46/head: file://patches/paxml/PR-46.patch # adds Transformer Engine support
praxis:
  url: https://github.com/google/praxis.git
  mirror_url: https://github.com/nvjax-svc-0/praxis.git
  tracking_ref: main
  latest_verified_commit: 7e179338d9e9cce1c01161a51e04b6f48c827945
  mode: git-clone
  patches:
    pull/27/head: file://patches/praxis/PR-27.patch # This PR allows XLA:GPU to detect the MHA pattern more easily to call fused kernels from cublas.
    pull/36/head: file://patches/praxis/PR-36.patch # adds Transformer Engine support
lingvo:
  # Used only in ARM pax builds
  url: https://github.com/tensorflow/lingvo.git
  tracking_ref: master
  latest_verified_commit: b663bb0c475a7d7a1d5bcd227069feca392a3f00
  mode: git-clone
tensorflow-text:
  # Used only in ARM pax and t5x builds
  url: https://github.com/tensorflow/text.git
  tracking_ref: v2.13.0
  latest_verified_commit: 917a681d7220ebf9b62a08b6f9ce7b7db886ddef
  mode: git-clone
pydantic:
  version: X.Y.Z
  mode: pip-constraint
# Used by praxis
fiddle:
  url: https://github.com/google/fiddle.git
  tracking_ref: main
  latest_verified_commit: 89d6c48b411d0ae7ee45b1acd84e838e414b7d16
  mode: pip-vcs
# Used by t5x
airio:
  url: https://github.com/google/airio.git
  tracking_ref: main
  latest_verified_commit: da74a259cc0e7a4b8b0b728c8deb0c182210bafd
  mode: pip-vcs
clu:
  url: https://github.com/google/CommonLoopUtils.git
  tracking_ref: main
  latest_verified_commit: 3fdcf85060fe27617a3092244e9ebc230ce680d2
  mode: pip-vcs
dllogger:
  url: https://github.com/NVIDIA/dllogger.git
  tracking_ref: master
  latest_verified_commit: 0478734ff7be75adde8d160e04872664d1c62e5f
  mode: pip-vcs
jestimator:
  url: https://github.com/google-research/jestimator.git
  tracking_ref: main
  latest_verified_commit: 326824a477feef6d92e6f44175000907a72899ca
  mode: pip-vcs
optax:
  url: https://github.com/google-deepmind/optax.git
  tracking_ref: main
  latest_verified_commit: 017a7a2a908a80171e4730e164547dd6985bc701
  mode: pip-vcs
seqio:
  url: https://github.com/google/seqio.git
  tracking_ref: main
  latest_verified_commit: db78942f10f9937ed42d42adf94c7f669b36fc84
  mode: pip-vcs
# used by Pallas
openxla-triton:
  url: https://github.com/openxla/triton.git
  tracking_ref: llvm-head
  latest_verified_commit: 4038c4a545d65b35b43b3866945ab515ce45ab1d
  mode: git-clone
jax-triton:
  url: https://github.com/jax-ml/jax-triton.git
  tracking_ref: main
  latest_verified_commit: a298a7884054d3fc4bf94e1cb3d2a3baa907ea6b
  mode: git-clone
maxtext:
  url: https://github.com/google/maxtext.git
  tracking_ref: main
  latest_verified_commit: 95ef3e1074f37126cfd2432b7d0376f24cb82632
  mode: git-clone
levanter:
  url: https://github.com/stanford-crfm/levanter.git
  tracking_ref: main
  latest_verified_commit: |-
    982cef7f1d8d1a642b825fcd30ab1b44a912f478
    f597e563037ab8d664c84bd16d53e071b9d728d5
  mode: git-clone
haliax:
  url: https://github.com/stanford-crfm/haliax.git
  tracking_ref: main
  latest_verified_commit: 280f49fb560f488063efd483b704172ca05b6476
  mode: git-clone
mujoco:
  url: https://github.com/google-deepmind/mujoco.git
  tracking_ref: main
  latest_verified_commit: d680b3d2341dd2a8c16f1f30fd4a13c8bf6639f4
  mode: git-clone
grain:
  # Used only in ARM t5x builds
  url: https://github.com/google/grain.git
  tracking_ref: main
  latest_verified_commit: 4ab3efff5a50716b3aa76cf4238af1cd5f82b14d
  mode: git-clone
mujoco-mpc:
  url: https://github.com/google-deepmind/mujoco_mpc.git
  tracking_ref: main
  latest_verified_commit: ff572a21e7c2bf9fda62e1862a758da7e9a8719b
  mode: git-clone
language-to-reward-2023:
  url: https://github.com/google-deepmind/language_to_reward_2023.git
  tracking_ref: main
  latest_verified_commit: 4a3a20f9c8705e3a3ded4d218d9c129303d9682e
  mode: git-clone
mlperf-logging:
  url: https://github.com/mlcommons/logging.git
  tracking_ref: master
  latest_verified_commit: 346e6046e16148ed095ffce5d9650f20e83b6858
  mode: pip-vcs
equinox:
  url: https://github.com/patrick-kidger/equinox.git
  tracking_ref: main
  latest_verified_commit: 14234c9cd390f05e5671f2fca76ea1356df63f46
  mode: git-clone
grok-1:
  url: https://github.com/xai-org/grok-1.git
  tracking_ref: main
  latest_verified_commit: 7050ed204b8206bb8645c7b7bbef7252f79561b0
  mode: git-clone
