jax:
  url: https://github.com/google/jax.git
  tracking_ref: main
  latest_verified_commit: aa9fdd3ca71c473e0496c5ab863f19bef04a5bf7
  mode: git-clone
xla:
  url: https://github.com/openxla/xla.git
  tracking_ref: main
  latest_verified_commit: 9fca413e8b4870914bd7aa4c690458b724e055f0
  mode: git-clone
flax:
  url: https://github.com/google/flax.git
  mirror_url: https://github.com/nvjax-svc-0/flax.git
  tracking_ref: main
  latest_verified_commit: cbb4f80f1ad8c3b659a0575516934ee332045028
  mode: git-clone
  patches:
    pull/3340/head: file://patches/flax/PR-3340.patch # Add Sharding Annotations to Flax Modules
transformer-engine:
  url: https://github.com/NVIDIA/TransformerEngine.git
  tracking_ref: main
  latest_verified_commit: 2f25d1212b9545bc0ad9a5b38a60afc1588f7329
  mode: git-clone
t5x:
  url: https://github.com/google-research/t5x.git
  mirror_url: https://github.com/nvjax-svc-0/t5x.git
  tracking_ref: main
  latest_verified_commit: 087c7242b43a158bf560bcb44ec5e8824cd1dbc6
  mode: git-clone
  patches:
    mirror/patch/partial-checkpoint-restore: file://patches/t5x/mirror-patch-partial-checkpoint-restore.patch # pull/1392/head  # https://github.com/google-research/t5x/pull/1392: Add support for partial checkpoint restore
    mirror/patch/dali-support: file://patches/t5x/mirror-patch-dali-support.patch # pull/1393/head  # https://github.com/google-research/t5x/pull/1393: Adds DALI support to t5x
    mirror/patch/t5x_te_in_contrib_noindent: file://patches/t5x/mirror-patch-t5x_te_in_contrib_noindent.patch # pull/1391/head  # https://github.com/google-research/t5x/pull/1391: Adds transformer engine support and GPU optimizations to T5x (enables H100)
paxml:
  url: https://github.com/google/paxml.git
  mirror_url: https://github.com/nvjax-svc-0/paxml.git
  tracking_ref: main
  latest_verified_commit: a62a3cd36894e808a0d2608e15f7ade1c70044c2
  mode: git-clone
  patches:
    pull/46/head: file://patches/paxml/PR-46.patch # adds Transformer Engine support
praxis:
  url: https://github.com/google/praxis.git
  mirror_url: https://github.com/nvjax-svc-0/praxis.git
  tracking_ref: main
  latest_verified_commit: 41191d22b702d5f86a1dd1a72e89c0d030c08aec
  mode: git-clone
  patches:
    pull/27/head: file://patches/praxis/PR-27.patch # This PR allows XLA:GPU to detect the MHA pattern more easily to call fused kernels from cublas.
    pull/36/head: file://patches/praxis/PR-36.patch # adds Transformer Engine support
lingvo:
  # Used only in ARM pax builds
  url: https://github.com/tensorflow/lingvo.git
  tracking_ref: master
  latest_verified_commit: 3540b55a2684c56febe588fbe6ae4875860af67b
  mode: git-clone
tensorflow-text:
  # Used only in ARM pax and t5x builds
  url: https://github.com/tensorflow/text.git
  tracking_ref: v2.13.0
  latest_verified_commit: 917a681d7220ebf9b62a08b6f9ce7b7db886ddef
  mode: git-clone
pydantic:
  version: X.Y.Z
  mode: pip-constraint
# Used by praxis
fiddle:
  url: https://github.com/google/fiddle.git
  tracking_ref: main
  latest_verified_commit: d2e56f8188ef8a509512cae88cd8740e1453f0e3
  mode: pip-vcs
# Used by t5x
airio:
  url: https://github.com/google/airio.git
  tracking_ref: main
  latest_verified_commit: 7feb9ddc2083dd219ffa947901cf61de9132a28a
  mode: pip-vcs
clu:
  url: https://github.com/google/CommonLoopUtils.git
  tracking_ref: main
  latest_verified_commit: 949e50380a67c934f1d10bcf241cb0c56d369289
  mode: pip-vcs
dllogger:
  url: https://github.com/NVIDIA/dllogger.git
  tracking_ref: master
  latest_verified_commit: 0478734ff7be75adde8d160e04872664d1c62e5f
  mode: pip-vcs
jestimator:
  url: https://github.com/google-research/jestimator.git
  tracking_ref: main
  latest_verified_commit: 326824a477feef6d92e6f44175000907a72899ca
  mode: pip-vcs
optax:
  url: https://github.com/google-deepmind/optax.git
  tracking_ref: main
  latest_verified_commit: a02de8401f7dc406a6324e8dec83c5526e6db249
  mode: pip-vcs
seqio:
  url: https://github.com/google/seqio.git
  tracking_ref: main
  latest_verified_commit: 49213270cc20aaafaa06814502aad655d9275936
  mode: pip-vcs
# used by Pallas
openxla-triton:
  url: https://github.com/openxla/triton.git
  tracking_ref: llvm-head
  latest_verified_commit: 4038c4a545d65b35b43b3866945ab515ce45ab1d
  mode: git-clone
jax-triton:
  url: https://github.com/jax-ml/jax-triton.git
  tracking_ref: main
  latest_verified_commit: 0581131ccd7cc9beac8c853d367f998acdf784bd
  mode: git-clone
maxtext:
  url: https://github.com/google/maxtext.git
  tracking_ref: main
  latest_verified_commit: 93930f692992519bee2bcc1f4cd18fe64e095592
  mode: git-clone
levanter:
  url: https://github.com/stanford-crfm/levanter.git
  tracking_ref: main
  latest_verified_commit: 8bb03926c85dd6175cdeb54a14099efa77a59be0
  mode: git-clone
haliax:
  url: https://github.com/stanford-crfm/haliax.git
  tracking_ref: main
  latest_verified_commit: be87443d026f8aa25b68582a34a51f3c76d1460a
  mode: git-clone
mujoco:
  url: https://github.com/google-deepmind/mujoco.git
  tracking_ref: main
  latest_verified_commit: a86461fc57a3f1c0a8ce1417fc1d13c2001273bc
  mode: git-clone
grain:
  # Used only in ARM t5x builds
  url: https://github.com/google/grain.git
  tracking_ref: main
  latest_verified_commit: 20d30bb3189288ae4704e2f71405cabc0c8f1285
  mode: git-clone
mujoco-mpc:
  url: https://github.com/google-deepmind/mujoco_mpc.git
  tracking_ref: main
  latest_verified_commit: ff572a21e7c2bf9fda62e1862a758da7e9a8719b
  mode: git-clone
language-to-reward-2023:
  url: https://github.com/google-deepmind/language_to_reward_2023.git
  tracking_ref: main
  latest_verified_commit: 4a3a20f9c8705e3a3ded4d218d9c129303d9682e
  mode: git-clone
mlperf-logging:
  url: https://github.com/mlcommons/logging.git
  tracking_ref: master
  latest_verified_commit: 44b4810e65e8c0a7d9e4e207c60e51d9458a3fb8
  mode: pip-vcs
equinox:
  url: https://github.com/patrick-kidger/equinox.git
  tracking_ref: main
  latest_verified_commit: 9a21f7c84dc65e1fae076679cdabe967dbf65d9f
  mode: git-clone
grok-1:
  url: https://github.com/xai-org/grok-1.git
  tracking_ref: main
  latest_verified_commit: 7050ed204b8206bb8645c7b7bbef7252f79561b0
  mode: git-clone
