jax:
  url: https://github.com/google/jax.git
  tracking_ref: main
  latest_verified_commit: 351c13e5b6dfec90863ef64f137a28da7426f38a
  mode: git-clone
xla:
  url: https://github.com/openxla/xla.git
  tracking_ref: main
  latest_verified_commit: e039a21a6ffa80bab553479d4a62054c08316e6e
  mode: git-clone
flax:
  url: https://github.com/google/flax.git
  mirror_url: https://github.com/nvjax-svc-0/flax.git
  tracking_ref: main
  latest_verified_commit: 54fad0a842074b72cde7743384a3d9f4449f35fa
  mode: git-clone
  patches:
    pull/3340/head: file://patches/flax/PR-3340.patch # Add Sharding Annotations to Flax Modules
transformer-engine:
  url: https://github.com/NVIDIA/TransformerEngine.git
  tracking_ref: main
  latest_verified_commit: 6c942ffdff6cc1f67b2ab569b5fc539774239443
  mode: git-clone
t5x:
  url: https://github.com/google-research/t5x.git
  mirror_url: https://github.com/nvjax-svc-0/t5x.git
  tracking_ref: main
  latest_verified_commit: 509d35e084c92780ac7c993b74fa0792d845a0da
  mode: git-clone
  patches:
    mirror/patch/partial-checkpoint-restore: file://patches/t5x/mirror-patch-partial-checkpoint-restore.patch # pull/1392/head  # https://github.com/google-research/t5x/pull/1392: Add support for partial checkpoint restore
    mirror/patch/dali-support: file://patches/t5x/mirror-patch-dali-support.patch # pull/1393/head  # https://github.com/google-research/t5x/pull/1393: Adds DALI support to t5x
    mirror/patch/t5x_te_in_contrib_noindent: file://patches/t5x/mirror-patch-t5x_te_in_contrib_noindent.patch # pull/1391/head  # https://github.com/google-research/t5x/pull/1391: Adds transformer engine support and GPU optimizations to T5x (enables H100)
paxml:
  url: https://github.com/google/paxml.git
  mirror_url: https://github.com/nvjax-svc-0/paxml.git
  tracking_ref: main
  latest_verified_commit: f79c1e0a50b950ccd00f6f82f3a700f0eaf8df8f
  mode: git-clone
  patches:
    pull/46/head: file://patches/paxml/PR-46.patch # adds Transformer Engine support
praxis:
  url: https://github.com/google/praxis.git
  mirror_url: https://github.com/nvjax-svc-0/praxis.git
  tracking_ref: main
  latest_verified_commit: 4f01af48ddd6fdc008eb460051916e4fd8595335
  mode: git-clone
  patches:
    pull/27/head: file://patches/praxis/PR-27.patch # This PR allows XLA:GPU to detect the MHA pattern more easily to call fused kernels from cublas.
    pull/36/head: file://patches/praxis/PR-36.patch # adds Transformer Engine support
lingvo:
  # Used only in ARM pax builds
  url: https://github.com/tensorflow/lingvo.git
  tracking_ref: master
  latest_verified_commit: a3f9f1e8579fd7ce35a8332fddd5acac83f8176f
  mode: git-clone
tensorflow-text:
  # Used only in ARM pax and t5x builds
  url: https://github.com/tensorflow/text.git
  tracking_ref: v2.13.0
  latest_verified_commit: 917a681d7220ebf9b62a08b6f9ce7b7db886ddef
  mode: git-clone
pydantic:
  version: X.Y.Z
  mode: pip-constraint
# Used by praxis
fiddle:
  url: https://github.com/google/fiddle.git
  tracking_ref: main
  latest_verified_commit: b73e7c1c30d2f709753d58f6c8c56d87867b529b
  mode: pip-vcs
# Used by t5x
airio:
  url: https://github.com/google/airio.git
  tracking_ref: main
  latest_verified_commit: 167cd612dffc64765c51afe218aa8e9391e0c56c
  mode: pip-vcs
clu:
  url: https://github.com/google/CommonLoopUtils.git
  tracking_ref: main
  latest_verified_commit: 7baf9ccfdcb889612ee8ea858a4e09b70b9a88a8
  mode: pip-vcs
dllogger:
  url: https://github.com/NVIDIA/dllogger.git
  tracking_ref: master
  latest_verified_commit: 0478734ff7be75adde8d160e04872664d1c62e5f
  mode: pip-vcs
jestimator:
  url: https://github.com/google-research/jestimator.git
  tracking_ref: main
  latest_verified_commit: 326824a477feef6d92e6f44175000907a72899ca
  mode: pip-vcs
optax:
  url: https://github.com/google-deepmind/optax.git
  tracking_ref: main
  latest_verified_commit: f445273631ed9fa34a08de3190ae17fad6bc2263
  mode: pip-vcs
seqio:
  url: https://github.com/google/seqio.git
  tracking_ref: main
  latest_verified_commit: 49213270cc20aaafaa06814502aad655d9275936
  mode: pip-vcs
# used by Pallas
openxla-triton:
  url: https://github.com/openxla/triton.git
  tracking_ref: llvm-head
  latest_verified_commit: 4038c4a545d65b35b43b3866945ab515ce45ab1d
  mode: git-clone
jax-triton:
  url: https://github.com/jax-ml/jax-triton.git
  tracking_ref: main
  latest_verified_commit: e009254dce8c0b32bdd43823e265a5e53efc00b3
  mode: git-clone
maxtext:
  url: https://github.com/google/maxtext.git
  tracking_ref: main
  latest_verified_commit: 291b91234ea822ed01f13cf01f38ecb4dd5b6c2c
  mode: git-clone
levanter:
  url: https://github.com/stanford-crfm/levanter.git
  tracking_ref: main
  latest_verified_commit: 333b3277ad5a7f913e0f8b0a9f9abdf928a70b1c
  mode: git-clone
haliax:
  url: https://github.com/stanford-crfm/haliax.git
  tracking_ref: main
  latest_verified_commit: e50adabf694c7541a6f351b9dfc2a5c999da5566
  mode: git-clone
mujoco:
  url: https://github.com/google-deepmind/mujoco.git
  tracking_ref: main
  latest_verified_commit: d3bc0544d39c0933067e493f4c1c7ebfd15ae9f3
  mode: git-clone
grain:
  # Used only in ARM t5x builds
  url: https://github.com/google/grain.git
  tracking_ref: main
  latest_verified_commit: 67f44c433222de55f7a3947d166660cfa12aa87f
  mode: git-clone
mujoco-mpc:
  url: https://github.com/google-deepmind/mujoco_mpc.git
  tracking_ref: main
  latest_verified_commit: 9bd2037498056a0ab9cf9463ab841e40fef54142
  mode: git-clone
language-to-reward-2023:
  url: https://github.com/google-deepmind/language_to_reward_2023.git
  tracking_ref: main
  latest_verified_commit: 4a3a20f9c8705e3a3ded4d218d9c129303d9682e
  mode: git-clone
mlperf-logging:
  url: https://github.com/mlcommons/logging.git
  tracking_ref: master
  latest_verified_commit: 44b4810e65e8c0a7d9e4e207c60e51d9458a3fb8
  mode: pip-vcs
equinox:
  url: https://github.com/patrick-kidger/equinox.git
  tracking_ref: main
  latest_verified_commit: d3d4eb9758a017b1caddbc5219fd09379e171681
  mode: git-clone
grok-1:
  url: https://github.com/xai-org/grok-1.git
  tracking_ref: main
  latest_verified_commit: 7050ed204b8206bb8645c7b7bbef7252f79561b0
  mode: git-clone
